---
- name: install httpd
  yum: name={{ item.package }}
  with_items:
  - { package: httpd }

- name: create directory httpd document root
  file:
    path=/data/web/docroot
    state=directory
    owner=apache
    group=apache
    mode=0755
    recurse=yes

- name: set apache virtual host configuration
  copy:
    src=http-vhost.conf
    dest=/etc/httpd/conf.d/http-vhost.conf
    owner=apache
    group=apache
    mode=0644

- name: copy index file
  copy:
    src=index.html
    dest=/data/web/docroot
    owner=apache
    group=apache
    mode=0755

- name: start httpd service
  service: 
    name: httpd
    state: started   
    enabled: yes
