
aws:
  # The property referenced below, AWS_ENABLED, is not set in the
  # 'unified config' supported by the spinnaker/spinnaker project. If you
  # copy/paste this section into a new rosco-local.yml file for use with a
  # pre-built Spinnaker image, make sure to either replace AWS_ENABLED
  # with SPINNAKER_AWS_ENABLED or to explicitly set the property's value
  # to true.
  enabled: true 
  bakeryDefaults:
    awsAssociatePublicIpAddress: true
    # To make use of share_with and copy_to, replace this template with aws-multi-ebs.json.
    # When using aws-multi-ebs.json or aws-multi-chroot.json make sure to set the SPINNAKER_AWS_DEFAULT_ACCOUNT env
    # variable to the account ID of the AWS account the Spinnaker instance is launched in.
    templateFile: aws-ebs.json
    defaultVirtualizationType: hvm
    baseImages:
    # AMIs sourced from: https://cloud-images.ubuntu.com/locator/ec2/
    # Images should be considered placeholders.
    - baseImage:
        id: amazon-linux
        shortDescription: AmazonLinux1
        detailedDescription: AWS Amazon Linux 1
        packageType: rpm
        templateFile: aws-ebs.json
      virtualizationSettings:
      - region: ap-northeast-2
        virtualizationType: hvm
        instanceType: t2.micro
        sourceAmi: ami-863090e8
        sshUserName: ec2-user
        spotPrice: 0
        spotPriceAutoProdcut: Linux/UNIX (Amazon VPC)
